[ALL]
#_benchmark=1
#_validate_objects=0

[Cache]
_cache_mode=1

[Calc]
_cache_mode=1

[ClipVtkm]
_cache_mode=1

[CutGeometry]
_cache_mode=1

[CutGeometryOld]
_cache_mode=1

[CuttingSurface]
_cache_mode=1

[CuttingSurfaceVtkm]
_cache_mode=1

[IsoSurface]
_cache_mode=1

[IsoSurfaceVtkm]
_cache_mode=1

[Tracer]
_cache_mode=1

[TestCellSearch]
_cache_mode=1

[TestInterpolation]
_cache_mode=1
