["alias"]
# when Tubes is requested, start Thicken
Tubes = "Thicken"
TubesOld = "Thicken"
Spheres = "Thicken"
SpheresOld = "Thicken"

["replace"]
renderer = [ "COVER", "BlenderRenderer", "ANARemote", "DisCOVERay", "OsgRenderer" ]
select = [ "Threshold", "CellSelect" ]
color = [ "Color", "ColorRandom" ]
clip = [ "CutGeometry", "ClipVtkm" ]
attribute = [ "AddAttribute", "AttachShader", "ColorAttribute", "EnableTransparency", "Variant" ]
